
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY IDENTITY,
    firstname VARCHAR (100) NOT NULL,
    lastname VARCHAR (100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
	phone VARCHAR(20) NOT NULL,
	address VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(10) NOT NULL CHECK (role IN('admin','manager','client')),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_resets (
    email VARCHAR(150) NOT NULL PRIMARY KEY,
	token VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


